---
all:
  hosts:
    nexus-01:
      ansible_host: "51.250.10.98"
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: "glubuchik"
    ansible_ssh_private_key_file: "/home/glubuchik/.ssh/aglubuchik"